### ISSUE TITLE
[REQ] new release

### ISSUE THREAD

**Issue by slitvinov** [rakshasa/libtorrent#97]
Could you please make a new release
https://github.com/rakshasa/libtorrent/releases

to include `RAK_CHECK_CXX11` in configuration https://github.com/rakshasa/libtorrent/commit/d32a537c5fee1158877f9f036dc1035563c4a35c

Thank you.

**Comment by timofonic** [comment]
I agree.

I think rakshasa needs more hands to manage the project. He's a brilliant person, I'm sure he's quite busy.

I think libtorrent is the best library ever, I hope other procotols would be able to have an as good implementation such as libtorrent.

I'm worried about libtorrent stagnating.

Thanks a lot!

**Comment by rakshasa** [comment]
This is very much the case, I've had a bad couple of years due to health issues and only gradually getting back to working full time on my main work project of which I'm the technical lead.

I have in many ways intentionally blocked out all rtorrent specific tasks just to keep things at a manageable level. Even though there has been people offering money for me to work on this, it's not been possible.

In the coming year I'm hoping to put aside some time to just focus on this project, and a lot of the queued up stuff are things that can be quickly merged/implemented. Yet the mental context shift kind of requires me to have a proper period where the only thing I need to think about is this.

Not to mention that my inbox is quite literally littered with a couple hundred emails, etc, that I haven't read.

**Comment by rakshasa** [comment]
Oh... and about the OP, no I won't make a release on 0.13.x with that change as it is the 'stable' branch. The mentioned rev would make it not compile on some platforms, so use HEAD until I make an unstable branch.

The current mainline branch will require C++11, and the TR1 stuff in case of GCC, and the whole codebase will be processed through clang's conversion thing that changes all kinds of loops and such from C++98/TR1 to the new C++11 format.

Did an experiment with that and it made the code much cleaner are easier to read.
